import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateWorkerSupervisorRelation1765404708546 implements MigrationInterface {
    name = 'UpdateWorkerSupervisorRelation1765404708546'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP CONSTRAINT "user_assigned_roles_assigned_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP CONSTRAINT "user_assigned_roles_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP CONSTRAINT "user_assigned_roles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" DROP CONSTRAINT "FK_804560ec0e32381a87370cafc56"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP CONSTRAINT "FK_ef0eed7f5e819f5ac6bfe11dac4"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP CONSTRAINT "FK_84668cdcd6abdb2bf27dab815c8"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP CONSTRAINT "FK_95712ab51d460bd91b7dba1b55b"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP CONSTRAINT "FK_f48a5f46db8d13a0c8dad0a435d"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP CONSTRAINT "FK_87a40c9c38aa917baff4aca82de"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP CONSTRAINT "FK_7c0c012c2f8e6578277c239ee61"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP CONSTRAINT "FK_22eb9437b91298ce0161b05ce94"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP CONSTRAINT "FK_51fb74b0eb9a50850da92d0533c"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP CONSTRAINT "FK_dbe85a9e696f4a310a30501b063"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP CONSTRAINT "FK_b81d7b8569bcc8f71e4b3efefa2"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" DROP CONSTRAINT "FK_236b4a4823e804dd97f3cf801e7"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" DROP CONSTRAINT "FK_dbf9ba601e43dd884585e53d0ce"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP CONSTRAINT "truck_deliveries_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP CONSTRAINT "truck_deliveries_site_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."production" DROP CONSTRAINT "FK_98d244de11086b5d2f296efb21f"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."equipment" DROP CONSTRAINT "FK_8790d3264c2a836541ca100c78f"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_user_assigned_roles_user_id"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_user_assigned_roles_role_id"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_user_assigned_roles_status"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_payout_distribution"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_payout_partner"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_partner_cnic"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_income_date"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_income_site"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_client_business_name"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_expense_site"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_expense_date"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_expense_category"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_labor_cost_site"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_labor_cost_date"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_labor_cnic"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_labor_site"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_delivery_site"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_delivery_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP CONSTRAINT "truck_deliveries_status_check"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP CONSTRAINT "user_assigned_roles_user_id_role_id_key"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" DROP CONSTRAINT "UQ_5aba3b98daab87c536e9c7d58dc"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" DROP CONSTRAINT "UQ_fa5b6365e8d996ec487500cf818"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" RENAME COLUMN "is_active" TO "updated_at"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" RENAME COLUMN "updated_at" TO "is_active"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" DROP COLUMN "permissions"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" DROP CONSTRAINT "user_roles_name_key"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP COLUMN "assigned_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP COLUMN "updated_comment"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."users" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" DROP COLUMN "distribution_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" DROP COLUMN "share_percentage"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" DROP COLUMN "payout_amount"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "period_start"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "period_end"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "total_revenue"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "total_expenses"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "total_profit"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "approved_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "approved_at"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "coal_mining"."profit_distributions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "share_percentage"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "mine_number"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP CONSTRAINT "UQ_7316fee3f67b04fe07e14908ee3"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "cnic"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "lease"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "loading_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "coal_price"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "company_commission"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "quantity_tons"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "total_price"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "coal_mining"."income_status_enum"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "truck_number"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "driver_name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "driver_phone"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "buyer_name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "vehicle_number"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "evidence_photos"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "coal_agent_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "onboarding_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "business_name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "owner_name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "owner_contact"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "munshi_name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "munshi_contact"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "document_files"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "payment_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "expense_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "labor_cost_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "account_type"`);
        await queryRunner.query(`DROP TYPE "coal_mining"."expenses_account_type_enum"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "payee_type"`);
        await queryRunner.query(`DROP TYPE "coal_mining"."expenses_payee_type_enum"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "labor_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "partner_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "evidence_photos"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "payment_proof"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "site_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "work_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "quantity_tons"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "rate_per_ton"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "evidence_photos"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" DROP COLUMN "labor_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "offboarding_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "coal_mining"."workers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "daily_wage"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "onboarding_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "cnic"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "father_name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "mobile_number"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "emergency_number"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "supervised_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "other_detail"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" DROP COLUMN "supervisor_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" DROP COLUMN "assigned_at"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."mining_sites" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."mining_sites" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "delivery_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "quantity_tons"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "total_price"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "buyer_name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "vehicle_number"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "evidence_photos"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ADD "role_name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ADD CONSTRAINT "UQ_85683c502a3882013c989f4ee35" UNIQUE ("role_name")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."users" ADD "status" character varying(50) DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" ADD "date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" ADD "amount" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "partner_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "amount" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "contact" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "profit_share" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "amount" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "source" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "phone" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "type" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "client_id" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" ADD "worker_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" ADD "hours" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" ADD "cost" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "role" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "contact" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "hourly_rate" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ADD "contact" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."mining_sites" ADD "status" character varying(50) DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."mining_sites" ADD "partner_id" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "truck_number" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "quantity" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "client_id" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" ADD "labor_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" ADD CONSTRAINT "UQ_236b4a4823e804dd97f3cf801e7" UNIQUE ("labor_id")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "site_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "work_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "quantity_tons" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "rate_per_ton" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "evidence_photos" text array NOT NULL DEFAULT '{}'[]`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "period_start" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "period_end" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "total_revenue" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "total_expenses" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "total_profit" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "approved_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "status" "coal_mining"."profit_distributions_status_enum" NOT NULL DEFAULT '() => "'pending'.profit_distributions_status_enum"'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "approved_by" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" ADD "distribution_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" ADD "share_percentage" numeric(5,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" ADD "payout_amount" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "share_percentage" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "cnic" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD CONSTRAINT "UQ_7316fee3f67b04fe07e14908ee3" UNIQUE ("cnic")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "address" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "lease" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "mine_number" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ADD "supervisor_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ADD CONSTRAINT "UQ_dbf9ba601e43dd884585e53d0ce" UNIQUE ("supervisor_id")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ADD "assigned_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "delivery_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "buyer_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "vehicle_number" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "quantity_tons" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "total_price" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "status" character varying(20) DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "evidence_photos" text array`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."mining_sites" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."mining_sites" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "truck_number" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "loading_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "driver_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "driver_phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "coal_price" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "company_commission" numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "buyer_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "vehicle_number" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "quantity_tons" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "total_price" numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "status" "coal_mining"."income_status_enum" NOT NULL DEFAULT '() => "'draft'.income_status_enum"'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "evidence_photos" text array NOT NULL DEFAULT '{}'[]`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "business_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "owner_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "owner_contact" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "munshi_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "munshi_contact" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "onboarding_date" date`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "document_files" text array NOT NULL DEFAULT '{}'[]`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "coal_agent_id" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ADD "name" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ADD CONSTRAINT "UQ_4a77d431a6b2ac981c342b13c94" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ADD "permissions" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ADD "is_active" boolean DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD "status" character varying(50) DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD "updated_comment" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD "assigned_by" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."users" ADD "phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."users" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "expense_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "evidence_photos" text array NOT NULL DEFAULT '{}'[]`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "labor_cost_id" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "account_type" "coal_mining"."expenses_account_type_enum"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "payee_type" "coal_mining"."expenses_payee_type_enum"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "payment_date" date`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "payment_proof" text array NOT NULL DEFAULT '{}'[]`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "labor_id" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "partner_id" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "cnic" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "start_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "end_date" date`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "father_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "address" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "mobile_number" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "emergency_number" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "supervised_by" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "daily_wage" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "onboarding_date" date`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "offboarding_date" date`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "other_detail" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "status" "coal_mining"."workers_status_enum" NOT NULL DEFAULT '() => "'active'.labor_status_enum"'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ALTER COLUMN "assigned_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ALTER COLUMN "assigned_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."users" ALTER COLUMN "full_name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" DROP CONSTRAINT "expense_categories_name_key"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" ADD CONSTRAINT "UQ_6bdb3db95dd955d3c701e935426" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP CONSTRAINT "FK_16c9665fe75123f53cea16dee3b"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ALTER COLUMN "site_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP CONSTRAINT "FK_80969a8a02569e19a4b00f90837"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ALTER COLUMN "amount" TYPE numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ALTER COLUMN "site_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ALTER COLUMN "total_cost" TYPE numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP CONSTRAINT "FK_f06ca6d15de612fc339464c3114"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ALTER COLUMN "site_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" DROP CONSTRAINT "FK_f9c911595b51f9e23ee95341c89"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ALTER COLUMN "site_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ALTER COLUMN "site_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."production" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."production" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."equipment" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."equipment" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" DROP CONSTRAINT "UQ_6bdb3db95dd955d3c701e935426"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" ADD CONSTRAINT "UQ_6bdb3db95dd955d3c701e935426" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" DROP CONSTRAINT "FK_83ce44667eb960cc678b744c1d7"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" ADD CONSTRAINT "UQ_83ce44667eb960cc678b744c1d7" UNIQUE ("labor_cost_id")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ADD CONSTRAINT "UQ_f9c911595b51f9e23ee95341c89" UNIQUE ("site_id")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD CONSTRAINT "UQ_5fef794ace9cf73ff45b03068de" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD CONSTRAINT "UQ_b732bb50d70060e60351cdc5e0b" UNIQUE ("role_id")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ALTER COLUMN "assigned_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."production" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."production" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."production" ALTER COLUMN "site_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."equipment" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."equipment" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE UNIQUE INDEX "expense_categories_name_key" ON "coal_mining"."expense_categories" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "expense_categories_pkey" ON "coal_mining"."expense_categories" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_5aba3b98daab87c536e9c7d58dc" ON "coal_mining"."labor_cost_workers" ("labor_cost_id", "labor_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "labor_cost_workers_pkey" ON "coal_mining"."labor_cost_workers" ("id") `);
        await queryRunner.query(`CREATE INDEX "idx_labor_cost_date" ON "coal_mining"."labor_costs" ("work_date") `);
        await queryRunner.query(`CREATE INDEX "idx_labor_cost_site" ON "coal_mining"."labor_costs" ("site_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "labor_costs_pkey" ON "coal_mining"."labor_costs" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "profit_distributions_pkey" ON "coal_mining"."profit_distributions" ("id") `);
        await queryRunner.query(`CREATE INDEX "idx_payout_partner" ON "coal_mining"."partner_payouts" ("partner_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "partner_payouts_pkey" ON "coal_mining"."partner_payouts" ("id") `);
        await queryRunner.query(`CREATE INDEX "idx_payout_distribution" ON "coal_mining"."partner_payouts" ("distribution_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "partners_pkey" ON "coal_mining"."partners" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_7316fee3f67b04fe07e14908ee3" ON "coal_mining"."partners" ("cnic") `);
        await queryRunner.query(`CREATE INDEX "idx_partner_cnic" ON "coal_mining"."partners" ("cnic") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_fa5b6365e8d996ec487500cf818" ON "coal_mining"."site_supervisors" ("site_id", "supervisor_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "site_supervisors_pkey" ON "coal_mining"."site_supervisors" ("id") `);
        await queryRunner.query(`CREATE INDEX "idx_delivery_site" ON "coal_mining"."truck_deliveries" ("site_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "truck_deliveries_pkey" ON "coal_mining"."truck_deliveries" ("id") `);
        await queryRunner.query(`CREATE INDEX "idx_delivery_date" ON "coal_mining"."truck_deliveries" ("delivery_date") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "mining_sites_pkey" ON "coal_mining"."mining_sites" ("id") `);
        await queryRunner.query(`CREATE INDEX "idx_income_site" ON "coal_mining"."income" ("site_id") `);
        await queryRunner.query(`CREATE INDEX "idx_income_date" ON "coal_mining"."income" ("loading_date") `);
        await queryRunner.query(`CREATE INDEX "idx_client_business_name" ON "coal_mining"."clients" ("business_name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "user_roles_name_key" ON "coal_mining"."user_roles" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "user_roles_pkey" ON "coal_mining"."user_roles" ("id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_assigned_roles_user_id" ON "coal_mining"."user_assigned_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_assigned_roles_status" ON "coal_mining"."user_assigned_roles" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "user_assigned_roles_user_id_role_id_key" ON "coal_mining"."user_assigned_roles" ("role_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_assigned_roles_role_id" ON "coal_mining"."user_assigned_roles" ("role_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "user_assigned_roles_pkey" ON "coal_mining"."user_assigned_roles" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_username_key" ON "coal_mining"."users" ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_pkey" ON "coal_mining"."users" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_email_key" ON "coal_mining"."users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_expense_site" ON "coal_mining"."expenses" ("site_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "expenses_pkey" ON "coal_mining"."expenses" ("id") `);
        await queryRunner.query(`CREATE INDEX "idx_expense_date" ON "coal_mining"."expenses" ("expense_date") `);
        await queryRunner.query(`CREATE INDEX "idx_expense_category" ON "coal_mining"."expenses" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "idx_labor_site" ON "coal_mining"."workers" ("site_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "labor_pkey" ON "coal_mining"."workers" ("id") `);
        await queryRunner.query(`CREATE INDEX "idx_labor_cnic" ON "coal_mining"."workers" ("cnic") `);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD CONSTRAINT "FK_5fef794ace9cf73ff45b03068de" FOREIGN KEY ("user_id") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD CONSTRAINT "FK_b732bb50d70060e60351cdc5e0b" FOREIGN KEY ("role_id") REFERENCES "coal_mining"."user_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD CONSTRAINT "FK_6bdebac632401bdea8cae648e1c" FOREIGN KEY ("partner_id") REFERENCES "coal_mining"."partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD CONSTRAINT "FK_16c9665fe75123f53cea16dee3b" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD CONSTRAINT "FK_80969a8a02569e19a4b00f90837" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD CONSTRAINT "FK_5761adee29a8e328e2aa57ce302" FOREIGN KEY ("client_id") REFERENCES "coal_mining"."clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" ADD CONSTRAINT "FK_83ce44667eb960cc678b744c1d7" FOREIGN KEY ("labor_cost_id") REFERENCES "coal_mining"."labor_costs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" ADD CONSTRAINT "FK_65ca8995d7ef223331623b0228b" FOREIGN KEY ("worker_id") REFERENCES "coal_mining"."workers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD CONSTRAINT "FK_f06ca6d15de612fc339464c3114" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ADD CONSTRAINT "FK_f9c911595b51f9e23ee95341c89" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."mining_sites" ADD CONSTRAINT "FK_1ff4ef9c8c3704f4ab8c4194e4f" FOREIGN KEY ("partner_id") REFERENCES "coal_mining"."partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD CONSTRAINT "FK_dec929e362ef0c7edf3d0e34792" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD CONSTRAINT "FK_d3b03f5fd52a5e9e84057f38f7c" FOREIGN KEY ("client_id") REFERENCES "coal_mining"."clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."production" ADD CONSTRAINT "FK_98d244de11086b5d2f296efb21f" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."equipment" ADD CONSTRAINT "FK_8790d3264c2a836541ca100c78f" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" ADD CONSTRAINT "FK_236b4a4823e804dd97f3cf801e7" FOREIGN KEY ("labor_id") REFERENCES "coal_mining"."workers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD CONSTRAINT "FK_dbe85a9e696f4a310a30501b063" FOREIGN KEY ("created_by") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD CONSTRAINT "FK_b81d7b8569bcc8f71e4b3efefa2" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD CONSTRAINT "FK_ef0eed7f5e819f5ac6bfe11dac4" FOREIGN KEY ("approved_by") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" ADD CONSTRAINT "FK_804560ec0e32381a87370cafc56" FOREIGN KEY ("distribution_id") REFERENCES "coal_mining"."profit_distributions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD CONSTRAINT "FK_84668cdcd6abdb2bf27dab815c8" FOREIGN KEY ("mine_number") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ADD CONSTRAINT "FK_dbf9ba601e43dd884585e53d0ce" FOREIGN KEY ("supervisor_id") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD CONSTRAINT "FK_957fc9a8dffca1914fecb4783f8" FOREIGN KEY ("created_by") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD CONSTRAINT "FK_95712ab51d460bd91b7dba1b55b" FOREIGN KEY ("created_by") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD CONSTRAINT "FK_87a40c9c38aa917baff4aca82de" FOREIGN KEY ("coal_agent_id") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD CONSTRAINT "FK_f48a5f46db8d13a0c8dad0a435d" FOREIGN KEY ("created_by") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD CONSTRAINT "FK_630cf9b03b9d58d5d3457b3d6d3" FOREIGN KEY ("assigned_by") REFERENCES "coal_mining"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD CONSTRAINT "FK_7c0c012c2f8e6578277c239ee61" FOREIGN KEY ("created_by") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD CONSTRAINT "FK_51fb74b0eb9a50850da92d0533c" FOREIGN KEY ("labor_id") REFERENCES "coal_mining"."workers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD CONSTRAINT "FK_22eb9437b91298ce0161b05ce94" FOREIGN KEY ("partner_id") REFERENCES "coal_mining"."partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP CONSTRAINT "FK_22eb9437b91298ce0161b05ce94"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP CONSTRAINT "FK_51fb74b0eb9a50850da92d0533c"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP CONSTRAINT "FK_7c0c012c2f8e6578277c239ee61"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP CONSTRAINT "FK_630cf9b03b9d58d5d3457b3d6d3"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP CONSTRAINT "FK_f48a5f46db8d13a0c8dad0a435d"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP CONSTRAINT "FK_87a40c9c38aa917baff4aca82de"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP CONSTRAINT "FK_95712ab51d460bd91b7dba1b55b"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP CONSTRAINT "FK_957fc9a8dffca1914fecb4783f8"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" DROP CONSTRAINT "FK_dbf9ba601e43dd884585e53d0ce"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP CONSTRAINT "FK_84668cdcd6abdb2bf27dab815c8"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" DROP CONSTRAINT "FK_804560ec0e32381a87370cafc56"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP CONSTRAINT "FK_ef0eed7f5e819f5ac6bfe11dac4"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP CONSTRAINT "FK_b81d7b8569bcc8f71e4b3efefa2"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP CONSTRAINT "FK_dbe85a9e696f4a310a30501b063"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" DROP CONSTRAINT "FK_236b4a4823e804dd97f3cf801e7"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."equipment" DROP CONSTRAINT "FK_8790d3264c2a836541ca100c78f"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."production" DROP CONSTRAINT "FK_98d244de11086b5d2f296efb21f"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP CONSTRAINT "FK_d3b03f5fd52a5e9e84057f38f7c"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP CONSTRAINT "FK_dec929e362ef0c7edf3d0e34792"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."mining_sites" DROP CONSTRAINT "FK_1ff4ef9c8c3704f4ab8c4194e4f"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" DROP CONSTRAINT "FK_f9c911595b51f9e23ee95341c89"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP CONSTRAINT "FK_f06ca6d15de612fc339464c3114"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" DROP CONSTRAINT "FK_65ca8995d7ef223331623b0228b"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" DROP CONSTRAINT "FK_83ce44667eb960cc678b744c1d7"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP CONSTRAINT "FK_5761adee29a8e328e2aa57ce302"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP CONSTRAINT "FK_80969a8a02569e19a4b00f90837"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP CONSTRAINT "FK_16c9665fe75123f53cea16dee3b"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP CONSTRAINT "FK_6bdebac632401bdea8cae648e1c"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP CONSTRAINT "FK_b732bb50d70060e60351cdc5e0b"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP CONSTRAINT "FK_5fef794ace9cf73ff45b03068de"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_labor_cnic"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."labor_pkey"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_labor_site"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_expense_category"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_expense_date"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."expenses_pkey"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_expense_site"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."users_email_key"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."users_pkey"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."users_username_key"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."user_assigned_roles_pkey"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_user_assigned_roles_role_id"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."user_assigned_roles_user_id_role_id_key"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_user_assigned_roles_status"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_user_assigned_roles_user_id"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."user_roles_pkey"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."user_roles_name_key"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_client_business_name"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_income_date"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_income_site"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."mining_sites_pkey"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_delivery_date"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."truck_deliveries_pkey"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_delivery_site"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."site_supervisors_pkey"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."UQ_fa5b6365e8d996ec487500cf818"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_partner_cnic"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."UQ_7316fee3f67b04fe07e14908ee3"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."partners_pkey"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_payout_distribution"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."partner_payouts_pkey"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_payout_partner"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."profit_distributions_pkey"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."labor_costs_pkey"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_labor_cost_site"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."idx_labor_cost_date"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."labor_cost_workers_pkey"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."UQ_5aba3b98daab87c536e9c7d58dc"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."expense_categories_pkey"`);
        await queryRunner.query(`DROP INDEX "coal_mining"."expense_categories_name_key"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."equipment" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."equipment" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."production" ALTER COLUMN "site_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."production" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."production" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ALTER COLUMN "assigned_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP CONSTRAINT "UQ_b732bb50d70060e60351cdc5e0b"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP CONSTRAINT "UQ_5fef794ace9cf73ff45b03068de"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" DROP CONSTRAINT "UQ_f9c911595b51f9e23ee95341c89"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" DROP CONSTRAINT "UQ_83ce44667eb960cc678b744c1d7"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" ADD CONSTRAINT "FK_83ce44667eb960cc678b744c1d7" FOREIGN KEY ("labor_cost_id") REFERENCES "coal_mining"."labor_costs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" DROP CONSTRAINT "UQ_6bdb3db95dd955d3c701e935426"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" ADD CONSTRAINT "UQ_6bdb3db95dd955d3c701e935426" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."equipment" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."equipment" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."production" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."production" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ALTER COLUMN "site_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ALTER COLUMN "site_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ADD CONSTRAINT "FK_f9c911595b51f9e23ee95341c89" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ALTER COLUMN "site_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD CONSTRAINT "FK_f06ca6d15de612fc339464c3114" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ALTER COLUMN "total_cost" TYPE numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ALTER COLUMN "site_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ALTER COLUMN "amount" TYPE numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD CONSTRAINT "FK_80969a8a02569e19a4b00f90837" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ALTER COLUMN "site_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD CONSTRAINT "FK_16c9665fe75123f53cea16dee3b" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" DROP CONSTRAINT "UQ_6bdb3db95dd955d3c701e935426"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" ADD CONSTRAINT "expense_categories_name_key" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."users" ALTER COLUMN "full_name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ALTER COLUMN "assigned_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ALTER COLUMN "assigned_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "other_detail"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "offboarding_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "onboarding_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "daily_wage"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "supervised_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "emergency_number"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "mobile_number"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "father_name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "cnic"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "partner_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "labor_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "payment_proof"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "payment_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "payee_type"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "account_type"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "labor_cost_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "evidence_photos"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "expense_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."users" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP COLUMN "assigned_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP COLUMN "updated_comment"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" DROP COLUMN "permissions"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" DROP CONSTRAINT "UQ_4a77d431a6b2ac981c342b13c94"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "coal_agent_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "document_files"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "onboarding_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "munshi_contact"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "munshi_name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "owner_contact"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "owner_name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "business_name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "evidence_photos"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "total_price"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "quantity_tons"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "vehicle_number"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "buyer_name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "company_commission"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "coal_price"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "driver_phone"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "driver_name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "loading_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "truck_number"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."mining_sites" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."mining_sites" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "evidence_photos"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "total_price"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "quantity_tons"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "vehicle_number"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "buyer_name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "delivery_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" DROP COLUMN "assigned_at"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" DROP CONSTRAINT "UQ_dbf9ba601e43dd884585e53d0ce"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" DROP COLUMN "supervisor_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "mine_number"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "lease"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP CONSTRAINT "UQ_7316fee3f67b04fe07e14908ee3"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "cnic"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "share_percentage"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" DROP COLUMN "payout_amount"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" DROP COLUMN "share_percentage"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" DROP COLUMN "distribution_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "approved_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "approved_at"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "total_profit"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "total_expenses"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "total_revenue"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "period_end"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "period_start"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "evidence_photos"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "rate_per_ton"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "quantity_tons"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "work_date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "site_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" DROP CONSTRAINT "UQ_236b4a4823e804dd97f3cf801e7"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" DROP COLUMN "labor_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "client_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "quantity"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "truck_number"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."mining_sites" DROP COLUMN "partner_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."mining_sites" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" DROP COLUMN "contact"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "hourly_rate"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "contact"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" DROP COLUMN "cost"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" DROP COLUMN "hours"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" DROP COLUMN "worker_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "client_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "source"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "profit_share"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" DROP COLUMN "contact"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" DROP COLUMN "partner_id"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."users" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" DROP CONSTRAINT "UQ_85683c502a3882013c989f4ee35"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" DROP COLUMN "role_name"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "evidence_photos" text array`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "status" character varying(20) DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "vehicle_number" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "buyer_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "total_price" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "quantity_tons" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD "delivery_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."mining_sites" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."mining_sites" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ADD "assigned_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ADD "supervisor_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "other_detail" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "supervised_by" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "emergency_number" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "mobile_number" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "address" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "father_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "cnic" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "onboarding_date" date`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "daily_wage" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "end_date" date`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "start_date" date NOT NULL`);
        await queryRunner.query(`CREATE TYPE "coal_mining"."workers_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "status" "coal_mining"."workers_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."workers" ADD "offboarding_date" date`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" ADD "labor_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "evidence_photos" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "rate_per_ton" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "quantity_tons" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "work_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD "site_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "payment_proof" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "evidence_photos" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "partner_id" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "labor_id" integer`);
        await queryRunner.query(`CREATE TYPE "coal_mining"."expenses_payee_type_enum" AS ENUM('labor', 'partner')`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "payee_type" "coal_mining"."expenses_payee_type_enum"`);
        await queryRunner.query(`CREATE TYPE "coal_mining"."expenses_account_type_enum" AS ENUM('employee', 'vendor', 'partner', 'other')`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "account_type" "coal_mining"."expenses_account_type_enum"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "labor_cost_id" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "expense_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD "payment_date" date`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "document_files" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "munshi_contact" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "munshi_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "owner_contact" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "owner_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "business_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "created_by" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "onboarding_date" date`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD "coal_agent_id" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "evidence_photos" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "vehicle_number" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "buyer_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "driver_phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "driver_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "truck_number" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "created_by" integer`);
        await queryRunner.query(`CREATE TYPE "coal_mining"."income_status_enum" AS ENUM('draft', 'completed')`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "status" "coal_mining"."income_status_enum" NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "total_price" numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "quantity_tons" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "company_commission" numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "coal_price" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD "loading_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "lease" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "address" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "cnic" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD CONSTRAINT "UQ_7316fee3f67b04fe07e14908ee3" UNIQUE ("cnic")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "mine_number" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD "share_percentage" numeric(5,2)`);
        await queryRunner.query(`CREATE TYPE "coal_mining"."profit_distributions_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "status" "coal_mining"."profit_distributions_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "approved_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "approved_by" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "total_profit" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "total_expenses" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "total_revenue" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "period_end" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD "period_start" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" ADD "payout_amount" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" ADD "share_percentage" numeric(5,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" ADD "distribution_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."users" ADD "phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."users" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD "status" character varying(50) DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD "updated_comment" text`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD "assigned_by" integer`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ADD "name" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ADD CONSTRAINT "user_roles_name_key" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ADD "is_active" boolean DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_roles" ADD "permissions" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" RENAME COLUMN "is_active" TO "updated_at"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expense_categories" RENAME COLUMN "updated_at" TO "is_active"`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ADD CONSTRAINT "UQ_fa5b6365e8d996ec487500cf818" UNIQUE ("site_id", "supervisor_id")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" ADD CONSTRAINT "UQ_5aba3b98daab87c536e9c7d58dc" UNIQUE ("labor_cost_id", "labor_id")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD CONSTRAINT "user_assigned_roles_user_id_role_id_key" UNIQUE ("user_id", "role_id")`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD CONSTRAINT "truck_deliveries_status_check" CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'completed'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "idx_delivery_date" ON "coal_mining"."truck_deliveries" ("delivery_date") `);
        await queryRunner.query(`CREATE INDEX "idx_delivery_site" ON "coal_mining"."truck_deliveries" ("site_id") `);
        await queryRunner.query(`CREATE INDEX "idx_labor_site" ON "coal_mining"."workers" ("site_id") `);
        await queryRunner.query(`CREATE INDEX "idx_labor_cnic" ON "coal_mining"."workers" ("cnic") `);
        await queryRunner.query(`CREATE INDEX "idx_labor_cost_date" ON "coal_mining"."labor_costs" ("work_date") `);
        await queryRunner.query(`CREATE INDEX "idx_labor_cost_site" ON "coal_mining"."labor_costs" ("site_id") `);
        await queryRunner.query(`CREATE INDEX "idx_expense_category" ON "coal_mining"."expenses" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "idx_expense_date" ON "coal_mining"."expenses" ("expense_date") `);
        await queryRunner.query(`CREATE INDEX "idx_expense_site" ON "coal_mining"."expenses" ("site_id") `);
        await queryRunner.query(`CREATE INDEX "idx_client_business_name" ON "coal_mining"."clients" ("business_name") `);
        await queryRunner.query(`CREATE INDEX "idx_income_site" ON "coal_mining"."income" ("site_id") `);
        await queryRunner.query(`CREATE INDEX "idx_income_date" ON "coal_mining"."income" ("loading_date") `);
        await queryRunner.query(`CREATE INDEX "idx_partner_cnic" ON "coal_mining"."partners" ("cnic") `);
        await queryRunner.query(`CREATE INDEX "idx_payout_partner" ON "coal_mining"."partner_payouts" ("partner_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payout_distribution" ON "coal_mining"."partner_payouts" ("distribution_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_assigned_roles_status" ON "coal_mining"."user_assigned_roles" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_user_assigned_roles_role_id" ON "coal_mining"."user_assigned_roles" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_assigned_roles_user_id" ON "coal_mining"."user_assigned_roles" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "coal_mining"."equipment" ADD CONSTRAINT "FK_8790d3264c2a836541ca100c78f" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."production" ADD CONSTRAINT "FK_98d244de11086b5d2f296efb21f" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD CONSTRAINT "truck_deliveries_site_id_fkey" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."truck_deliveries" ADD CONSTRAINT "truck_deliveries_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."site_supervisors" ADD CONSTRAINT "FK_dbf9ba601e43dd884585e53d0ce" FOREIGN KEY ("supervisor_id") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_cost_workers" ADD CONSTRAINT "FK_236b4a4823e804dd97f3cf801e7" FOREIGN KEY ("labor_id") REFERENCES "coal_mining"."workers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD CONSTRAINT "FK_b81d7b8569bcc8f71e4b3efefa2" FOREIGN KEY ("site_id") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."labor_costs" ADD CONSTRAINT "FK_dbe85a9e696f4a310a30501b063" FOREIGN KEY ("created_by") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD CONSTRAINT "FK_51fb74b0eb9a50850da92d0533c" FOREIGN KEY ("labor_id") REFERENCES "coal_mining"."workers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD CONSTRAINT "FK_22eb9437b91298ce0161b05ce94" FOREIGN KEY ("partner_id") REFERENCES "coal_mining"."partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."expenses" ADD CONSTRAINT "FK_7c0c012c2f8e6578277c239ee61" FOREIGN KEY ("created_by") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD CONSTRAINT "FK_87a40c9c38aa917baff4aca82de" FOREIGN KEY ("coal_agent_id") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."clients" ADD CONSTRAINT "FK_f48a5f46db8d13a0c8dad0a435d" FOREIGN KEY ("created_by") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."income" ADD CONSTRAINT "FK_95712ab51d460bd91b7dba1b55b" FOREIGN KEY ("created_by") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partners" ADD CONSTRAINT "FK_84668cdcd6abdb2bf27dab815c8" FOREIGN KEY ("mine_number") REFERENCES "coal_mining"."mining_sites"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."profit_distributions" ADD CONSTRAINT "FK_ef0eed7f5e819f5ac6bfe11dac4" FOREIGN KEY ("approved_by") REFERENCES "coal_mining"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."partner_payouts" ADD CONSTRAINT "FK_804560ec0e32381a87370cafc56" FOREIGN KEY ("distribution_id") REFERENCES "coal_mining"."profit_distributions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD CONSTRAINT "user_assigned_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "coal_mining"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD CONSTRAINT "user_assigned_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "coal_mining"."user_roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coal_mining"."user_assigned_roles" ADD CONSTRAINT "user_assigned_roles_assigned_by_fkey" FOREIGN KEY ("assigned_by") REFERENCES "coal_mining"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
